// 80个国家的中英文名称映射
export const COUNTRY_NAMES_CN: Record<string, string> = {
  'Afghanistan': '阿富汗',
  'Algeria': '阿尔及利亚',
  'Angola': '安哥拉',
  'Argentina': '阿根廷',
  'Australia': '澳大利亚',
  'Bangladesh': '孟加拉国',
  'Benin': '贝宁',
  'Bolivia': '玻利维亚',
  'Brazil': '巴西',
  'Burkina Faso': '布基纳法索',
  'Burundi': '布隆迪',
  'Cambodia': '柬埔寨',
  'Cameroon': '喀麦隆',
  'Canada': '加拿大',
  'Chad': '乍得',
  'Chile': '智利',
  'China': '中国',
  'Colombia': '哥伦比亚',
  'Côte d\'Ivoire': '科特迪瓦',
  'Ecuador': '厄瓜多尔',
  'Egypt': '埃及',
  'Ethiopia': '埃塞俄比亚',
  'France': '法国',
  'Germany': '德国',
  'Ghana': '加纳',
  'Guatemala': '危地马拉',
  'Guinea': '几内亚',
  'Haiti': '海地',
  'India': '印度',
  'Indonesia': '印度尼西亚',
  'Iran': '伊朗',
  'Iraq': '伊拉克',
  'Italy': '意大利',
  'Japan': '日本',
  'Jordan': '约旦',
  'Kazakhstan': '哈萨克斯坦',
  'Kenya': '肯尼亚',
  'Madagascar': '马达加斯加',
  'Malawi': '马拉维',
  'Malaysia': '马来西亚',
  'Mali': '马里',
  'Mexico': '墨西哥',
  'Morocco': '摩洛哥',
  'Mozambique': '莫桑比克',
  'Myanmar': '缅甸',
  'Nepal': '尼泊尔',
  'Niger': '尼日尔',
  'Nigeria': '尼日利亚',
  'North Korea': '朝鲜',
  'Pakistan': '巴基斯坦',
  'Papua New Guinea': '巴布亚新几内亚',
  'Peru': '秘鲁',
  'Philippines': '菲律宾',
  'Poland': '波兰',
  'Russia': '俄罗斯',
  'Rwanda': '卢旺达',
  'Saudi Arabia': '沙特阿拉伯',
  'Senegal': '塞内加尔',
  'Sierra Leone': '塞拉利昂',
  'Somalia': '索马里',
  'South Africa': '南非',
  'South Korea': '韩国',
  'South Sudan': '南苏丹',
  'Spain': '西班牙',
  'Sri Lanka': '斯里兰卡',
  'Sudan': '苏丹',
  'Syria': '叙利亚',
  'Tanzania': '坦桑尼亚',
  'Thailand': '泰国',
  'Togo': '多哥',
  'Turkey': '土耳其',
  'Ukraine': '乌克兰',
  'United Kingdom': '英国',
  'United States': '美国',
  'Uzbekistan': '乌兹别克斯坦',
  'Venezuela': '委内瑞拉',
  'Vietnam': '越南',
  'Yemen': '也门',
  'Zambia': '赞比亚',
  'Zimbabwe': '津巴布韦',
};

// 80个国家的英文名称列表
export const COUNTRY_NAMES_EN: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_NAMES_CN).map(([en, cn]) => [cn, en])
);

// 获取国家中文名称，如果没有映射则返回英文名称
export function getCountryNameCN(englishName: string): string {
  return COUNTRY_NAMES_CN[englishName] || englishName;
}
